# Generated by Django 3.2.6 on 2023-09-19 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill_OP',
            fields=[
                ('Bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('Pay_status', models.BooleanField(null=True)),
                ('billdate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Custormer',
            fields=[
                ('custormer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_contact', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('Farmer_id', models.AutoField(primary_key=True, serialize=False)),
                ('Farmer_name', models.CharField(max_length=255)),
                ('Farmer_contact', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_description', models.CharField(max_length=255)),
                ('product_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Production_Bill',
            fields=[
                ('Production_Bill_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Car_driver', models.CharField(max_length=255)),
                ('H_Qty', models.IntegerField(null=True)),
                ('T_Qty', models.IntegerField(null=True)),
                ('M_Qty', models.IntegerField(null=True)),
                ('L_Qty', models.IntegerField(null=True)),
                ('H_Price', models.IntegerField(null=True)),
                ('T_Price', models.IntegerField(null=True)),
                ('M_Price', models.IntegerField(null=True)),
                ('L_Price', models.IntegerField(null=True)),
                ('Pay_status', models.BooleanField(null=True)),
                ('Production_Date', models.DateTimeField()),
                ('Bill_OP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.bill_op')),
                ('Custormer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.custormer')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Bill',
            fields=[
                ('Order_Bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('Qty', models.IntegerField()),
                ('Total_price', models.IntegerField()),
                ('Order_Date', models.DateTimeField()),
                ('Bill_OP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.bill_op')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.product')),
            ],
        ),
        migrations.AddField(
            model_name='bill_op',
            name='Farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.farmer'),
        ),
    ]
