# Generated by Django 3.2.6 on 2023-09-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill_op',
            name='Pay_status',
            field=models.BooleanField(default=False),
        ),
    ]
