# Generated by Django 3.2.6 on 2023-09-24 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_bill_op_pay_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill_op',
            name='Farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.farmer'),
        ),
        migrations.AlterField(
            model_name='order_bill',
            name='Bill_OP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.bill_op'),
        ),
        migrations.AlterField(
            model_name='order_bill',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.product'),
        ),
        migrations.AlterField(
            model_name='production_bill',
            name='Bill_OP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.bill_op'),
        ),
        migrations.AlterField(
            model_name='production_bill',
            name='Custormer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.custormer'),
        ),
    ]
