# Generated by Django 3.2.6 on 2023-09-25 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20230924_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='production_bill',
            name='H_Price_c',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='production_bill',
            name='L_Price_c',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='production_bill',
            name='M_Price_c',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='production_bill',
            name='T_Price_c',
            field=models.IntegerField(null=True),
        ),
    ]
