# Generated by Django 3.2.6 on 2023-09-25 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20230925_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production_BILL_Count',
            fields=[
                ('Production_Bill_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Car_driver', models.CharField(max_length=255)),
                ('H_Qty', models.IntegerField(null=True)),
                ('T_Qty', models.IntegerField(null=True)),
                ('M_Qty', models.IntegerField(null=True)),
                ('L_Qty', models.IntegerField(null=True)),
                ('H_Price', models.IntegerField(null=True)),
                ('T_Price', models.IntegerField(null=True)),
                ('M_Price', models.IntegerField(null=True)),
                ('L_Price', models.IntegerField(null=True)),
                ('H_Price_c', models.IntegerField(null=True)),
                ('T_Price_c', models.IntegerField(null=True)),
                ('M_Price_c', models.IntegerField(null=True)),
                ('L_Price_c', models.IntegerField(null=True)),
                ('Pay_status', models.BooleanField(null=True)),
                ('Production_Date', models.DateTimeField()),
                ('Bill_OP', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.bill_op')),
                ('Custormer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.custormer')),
            ],
        ),
    ]
