# Generated by Django 3.2.6 on 2023-09-25 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_production_bill_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Production_BILL_Count',
        ),
    ]
