# Generated by Django 3.2.6 on 2023-09-25 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_delete_production_bill_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill_op',
            name='Farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.farmer'),
        ),
    ]
