# Generated by Django 3.2.6 on 2023-09-25 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_bill_op_farmer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_bill',
            name='Bill_OP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.bill_op'),
        ),
        migrations.AlterField(
            model_name='order_bill',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.product'),
        ),
        migrations.AlterField(
            model_name='production_bill',
            name='Bill_OP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.bill_op'),
        ),
        migrations.AlterField(
            model_name='production_bill',
            name='Custormer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.custormer'),
        ),
    ]
