# Generated by Django 3.2.6 on 2023-09-25 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20230925_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('Exchange_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField(null=True)),
                ('iscomplete', models.BooleanField(null=True)),
                ('Bill_OP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.bill_op')),
            ],
        ),
    ]
